CREATE TABLE public.cost_plans (
    plan character varying(255) NOT NULL,
    cost numeric(38,2) NOT NULL,
    duration numeric(21,0) NOT NULL,
    CONSTRAINT cost_plans_plan_check CHECK (((plan)::text = ANY ((ARRAY['BASE'::character varying, 'PREMIUM'::character varying])::text[])))
);

CREATE TABLE public.movies (
    id bigint NOT NULL,
    description character varying(2000) NOT NULL,
    duration numeric(21,0) NOT NULL,
    genre character varying(255) NOT NULL,
    rating double precision,
    release_date date NOT NULL,
    required_plan character varying(255) NOT NULL,
    title character varying(255) NOT NULL,
    CONSTRAINT movies_genre_check CHECK (((genre)::text = ANY ((ARRAY['ACTION'::character varying, 'COMEDY'::character varying, 'DRAMA'::character varying, 'HORROR'::character varying, 'DOCUMENTAL'::character varying])::text[]))),
    CONSTRAINT movies_required_plan_check CHECK (((required_plan)::text = ANY ((ARRAY['BASE'::character varying, 'PREMIUM'::character varying])::text[])))
);

ALTER TABLE public.movies ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.movies_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.subscriptions (
    id bigint NOT NULL,
    cost numeric(38,2) NOT NULL,
    date_begin timestamp(6) with time zone NOT NULL,
    date_end timestamp(6) with time zone NOT NULL,
    plan character varying(255) NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT subscriptions_plan_check CHECK (((plan)::text = ANY ((ARRAY['BASE'::character varying, 'PREMIUM'::character varying])::text[])))
);

ALTER TABLE public.subscriptions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.subscriptions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.users (
    id bigint NOT NULL,
    display_name character varying(255) NOT NULL,
    is_deleted boolean NOT NULL,
    login character varying(255) NOT NULL,
    password_hash character varying(255) NOT NULL
);


ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.cost_plans
    ADD CONSTRAINT cost_plans_pkey PRIMARY KEY (plan);


ALTER TABLE ONLY public.movies
    ADD CONSTRAINT movies_pkey PRIMARY KEY (id);


ALTER TABLE ONLY public.subscriptions
    ADD CONSTRAINT subscriptions_pkey PRIMARY KEY (id);


ALTER TABLE ONLY public.users
    ADD CONSTRAINT ukow0gan20590jrb00upg3va2fn UNIQUE (login);


ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


ALTER TABLE ONLY public.subscriptions
    ADD CONSTRAINT fkhro52ohfqfbay9774bev0qinr FOREIGN KEY (user_id) REFERENCES public.users(id);
